# - include: tasks/install_java8.yml

- name: create consumer user
  user: name=reflinkconsumer state=present

- name: create and give worker ownership of log file
  file: path=/var/log/reflink-agent.log owner=reflink-agent state=touch mode=0666

- name: copy startup script
  copy: src=files/start_kcl dest=/opt/reflink/bin/start_kcl mode="u=rwx,g=r,o=r"

- name: populate consumer properties
  template: src=templates/consumer.properties dest=/opt/reflink/bin/consumer.properties mode="u=rwx,g=r,o=r"

- name: copy oldschool service script (for AWS AMI, Centos/RHEL <=6)
  copy: src=files/reflink-consumer dest=/etc/init.d/reflink-consumer mode=0755

- name: get kinesis client library
  git: repo=https://github.com/awslabs/amazon-kinesis-client-python.git dest=/tmp/amazon-kinesis-client-python

- name: download jars for KCL
  get_url:
    url: http://search.maven.org/remotecontent?filepath={{ item.group }}/{{ item.artifact_id }}/{{ item.version }}/{{ item.artifact_id }}-{{ item.version }}.jar
    dest: /opt/reflink/jars/{{ item.artifact_id }}-{{ item.version }}.jar
  with_items:
    - group: com/amazonaws
      artifact_id: amazon-kinesis-client
      version: 1.7.6
    - group: com/amazonaws
      artifact_id: aws-java-sdk-dynamodb
      version: 1.11.151
    - group: com/amazonaws
      artifact_id: aws-java-sdk-s3
      version: 1.11.151
    - group: com/amazonaws
      artifact_id: aws-java-sdk-kms
      version: 1.11.151
    - group: com/amazonaws
      artifact_id: aws-java-sdk-core
      version: 1.11.151
    - group: org/apache/httpcomponents
      artifact_id: httpclient
      version: 4.5.2
    - group: org/apache/httpcomponents
      artifact_id: httpcore
      version: 4.4.4
    - group: commons-codec
      artifact_id: commons-codec
      version: 1.9
    - group: software/amazon/ion
      artifact_id: ion-java
      version: 1.0.2
    - group: com/fasterxml/jackson/core
      artifact_id: jackson-databind
      version: 2.6.6
    - group: com/fasterxml/jackson/core
      artifact_id: jackson-databind
      version: 2.6.6
    - group: com/fasterxml/jackson/core
      artifact_id: jackson-annotations
      version: 2.6.0
    - group: com/fasterxml/jackson/core
      artifact_id: jackson-core
      version: 2.6.6
    - group: com/fasterxml/jackson/dataformat
      artifact_id: jackson-dataformat-cbor
      version: 2.6.6
    - group: joda-time
      artifact_id: joda-time
      version: 2.8.1
    - group: com/amazonaws
      artifact_id: jmespath-java
      version: 1.11.151
    - group: com/amazonaws
      artifact_id: aws-java-sdk-kinesis
      version: 1.11.151
    - group: com/amazonaws
      artifact_id: aws-java-sdk-cloudwatch
      version: 1.11.151
    - group: com/google/guava
      artifact_id: guava
      version: 18.0
    - group: com/google/protobuf
      artifact_id: protobuf-java
      version: 2.6.1
    - group: commons-lang
      artifact_id: commons-lang
      version: 2.6
    - group: commons-logging
      artifact_id: commons-logging
      version: 1.1.3

- name: give consumer user ownership of the application tree
  file: path=/opt/reflink owner=reflinkconsumer recurse=yes

- name: enable and start service
  service: name=reflink-consumer enabled=yes state=restarted
