- name: make sure that gcc is installed
  yum: name=gcc state=present

- name: install libcurl-devel.x86_64
  yum: name=libcurl-devel.x86_64 state=present

- name: install python3
  yum:
    name:
      - python35
      - python35-devel
    state: present

- name: get pip installer
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/usr/src

- name: install pip
  command: python3 /usr/src/get-pip.py

- name: upgrade pip
  pip:
    executable: /usr/local/bin/pip3
    name: pip
    state: latest

- name: enable epel repos
  yum: name=epel-release state=present

- name: install git
  yum: name=git state=present

- name: install virtualenv
  pip:
    executable: /usr/local/bin/pip3
    name: virtualenv

- name: create app tree
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/reflink
    - /opt/reflink/jars
    - /opt/reflink/bin
    - /opt/reflink/arxiv-reflink

- name: make sure zip/unzip are installed
  yum:
    name:
      - zip
      - unzip
    state: present

- name: unarchive reflink source
  unarchive:
    src: files/reflink.zip
    dest: /opt/reflink/arxiv-reflink
    force: yes

- name: create app virtualenv
  command: virtualenv /opt/reflink/venv --python=python3
  args:
    creates: /opt/reflink/venv

- name: upgrade pip
  pip: executable=/opt/reflink/venv/bin/pip3 name=pip state=latest

- name: upgrade setuptools
  pip: executable=/opt/reflink/venv/bin/pip3 name=setuptools state=latest

- name: install pycurl
  pip:
    executable: /opt/reflink/venv/bin/pip3
    name: pycurl
    state: latest
    extra_args: --install-option='--with-nss'

- name: install python dependencies for app
  pip: executable=/opt/reflink/venv/bin/pip3 requirements=/opt/reflink/arxiv-reflink/requirements.txt

- name: copy configuration secrets
  template: src=templates/secrets dest=/opt/reflink/secrets
