- name: make sure gcc and friends are installed
  yum:
    name:
      - gcc
      - make
      - zlib-devel
      - bzip2-devel
      - openssl-devel
      - ncurses-devel
    state: present


- name: make sure tar is installed
  yum:
    name:
      - tar
    state: present


- name: get Python3.6 source
  unarchive:
    src: https://www.python.org/ftp/python/3.6.1/Python-3.6.1.tgz
    dest: /usr/src
    creates: /usr/src/Python-3.6.1
    remote_src: yes


- name: configure Python build
  command: ./configure --prefix=/opt/
  args:
    chdir: /usr/src/Python-3.6.1
    creates: /usr/src/Python-3.6.1/Makefile


- name: build Python from source
  command: make
  args:
    chdir: /usr/src/Python-3.6.1
    creates: /usr/src/Python-3.6.1/libpython3.6m.a


- name: install Python (as root)
  command: make altinstall
  args:
    chdir: /usr/src/Python-3.6.1
    creates: /opt/bin/python3.6

- name: get pip installer
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /usr/src


- name: install pip
  command: /opt/bin/python3.6 /usr/src/get-pip.py
