---

# - name: Install base configuration on reflink hosts.
#   hosts: reflink-agent:reflink-worker
#   vars_files:
#     - vars/secrets.yml
#     - vars/general.yml
#   vars:
#     - reflink_user: reflink
#     - aws_region: us-east-1
#     - s3_bucket: "arxiv-reflink-proto"
#     - application_root: "/"
#     - reflink_base_url: "{{ groups['reflink-web'][0] }}/references"
#     - cermine_docker_image: "626657773168.dkr.ecr.us-east-1.amazonaws.com/arxiv/cermine"
#     - autotex_docker_image: "626657773168.dkr.ecr.us-east-1.amazonaws.com/arxiv/autotex"
#     - grobid_host: "{{ groups['reflink-scienceparse'][0] }}"
#     - scienceparse_host: "{{ groups['reflink-scienceparse'][0] }}"
#   roles:
#     - reflink
#
# - name: Install agent role
#   hosts: reflink-agent
#   vars:
#     - reflink_user: reflink
#     - aws_region: us-east-1
#     - s3_bucket: "arxiv-reflink-proto"
#   roles:
#     - agent
#   become: true

- name: Start Grobid & ScienceParse on worker.
  hosts: reflink-scienceparse
  vars_files:
    - vars/secrets.yml
    - vars/general.yml
  tasks:
    - name: make sure that docker-py is installed
      pip: name=docker-py state=latest
    - name: make sure that docker is installed
      yum: name=docker state=latest
    - name: ensure that docker is running
      service: name=docker state=running
    - name: add ec2-user to the docker group
      user: name=ec2-user group=docker append=yes
    - name: log in to docker
      shell: $(aws ecr get-login --region=us-east-1)
    - name: start Grobid
      docker_container:
        name: grobid
        image: "{{ grobid_docker_image }}"
        state: started
        pull: yes
        tty: yes
        ports: "{{ grobid_exposed_port }}:{{ grobid_local_port }}"
    # - name: start ScienceParse
    #   docker_container:
    #     name: scienceparse
    #     image: "{{ scienceparse_docker_image }}"
    #     state: started
    #     pull: yes
    #     tty: yes
    #     ports: "{{ scienceparse_exposed_port }}:{{ scienceparse_local_port }}"


# - name: Install worker role
#   hosts: reflink-worker
#   vars:
#     - reflink_user: reflink
#     - aws_region: us-east-1
#     - s3_bucket: "arxiv-reflink-proto"
#     - reflink_base_url: "{{ groups['web'][0] }}"
#   vars_files:
#     - vars/secrets.yml
#   roles:
#     - worker
#   become: true



# - name: Install web role
#   hosts: reflink-web
#   vars_files:
#     - vars/secrets.yml
#   vars:
#     - aws_region: us-east-1
#     - s3_bucket: "arxiv-reflink-proto"
#     - application_root: "/"
#     - cermine_docker_image: "626657773168.dkr.ecr.us-east-1.amazonaws.com/arxiv/cermine"
#     - autotex_docker_image: "626657773168.dkr.ecr.us-east-1.amazonaws.com/arxiv/autotex"
#   roles:
#     - web
#   become: true
