- hosts: localhost
  connection: local
  gather_facts: no
  environment:
    PYTHONPATH: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/:$PYTHONPATH
    TMPDIR: /tmp
  tasks:
    - name: create docker network
      docker_network:
        name: reflink_network
        ipam_options:
          subnet: 192.168.0.0/24
          gateway: 192.168.0.1
    - name: get the latest version of localstack
      git:
        repo: http://github.com/atlassian/localstack.git
        dest: /tmp/localstack
        depth: 1
        force: yes
    - name: launch localstack with docker-compose
      environment:
        TMPDIR: /tmp
      docker_service:
        project_src: /tmp/localstack
        debug: yes
        timeout: 30
