- name: make sure that docker-py is installed
  pip: name=docker-py state=latest

- name: make sure docker is installed
  yum: name=docker state=latest

- name: make sure that ghostscript is installed (provides ps2pdf)
  yum: name=ghostscript state=latest

- name: make sure docker is running
  service: name=docker state=started

- name: create worker user
  user: name=reflinkworker groups=docker state=present

- name: give worker ownership of log file
  file: path=/var/log/reflink-worker.log owner=reflinkworker state=touch mode=0666

- name: register with docker registry
  shell: |
    export AWS_ACCESS_KEY_ID="{{ aws_access_key }}"
    export AWS_SECRET_ACCESS_KEY="{{ aws_secret_key }}"
    $(aws ecr get-login --region=us-east-1)
  become_user: reflinkworker

- name: copy startup assets
  copy:
    src: files/start_worker
    dest: /opt/reflink/bin/start_worker
    mode: "u=rwx,g=r,o=r"

- name: copy oldschool service script (for AWS AMI, Centos/RHEL <=6)
  copy:
    src: files/reflink-worker
    dest: /etc/init.d/reflink-worker
    mode: 0755
    owner: reflinkworker

  # when: "'ec2hosts' in group_names"

- name: create log file
  file:
    path: /var/log/reflink-worker.log
    state: touch

- name: give worker user ownership of the application tree
  file: path=/opt/reflink owner=reflinkworker recurse=yes


- name: enable and start service
  service: name=reflink-worker enabled=yes state=restarted
